<?php

    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/lib/config.php";
    require_once "$root/panel/internationalization/Translate.php";

    $t = new Translate();
?>
<!DOCTYPE html>
<html lang="en">

	<!-- begin::Head -->
	<head>
		<meta charset="utf-8" />
		<title><?=$TITULO?></title>
		<meta name="description" content="Latest updates and statistic charts">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

		<!--begin::Web font -->
		<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
		<script>
			WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
        </script>

		<!--end::Web font -->

		<!--begin:: Global Mandatory Vendors -->
		<link href="./assets/vendors/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" type="text/css" />
		<!--end:: Global Mandatory Vendors -->

		<!--begin:: Global Optional Vendors -->
		<link href="./assets/vendors/tether/dist/css/tether.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-datetime-picker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-select/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/select2/dist/css/select2.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/nouislider/distribute/nouislider.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/owl.carousel/dist/assets/owl.carousel.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/owl.carousel/dist/assets/owl.theme.default.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/ion-rangeslider/css/ion.rangeSlider.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/ion-rangeslider/css/ion.rangeSlider.skinFlat.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/dropzone/dist/dropzone.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/summernote/dist/summernote.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/animate.css/animate.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/toastr/build/toastr.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/jstree/dist/themes/default/style.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/morris.js/morris.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/chartist/dist/chartist.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/socicon/css/socicon.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/vendors/line-awesome/css/line-awesome.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/vendors/flaticon/css/flaticon.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/vendors/metronic/css/styles.css" rel="stylesheet" type="text/css" />
		<link href="./assets/vendors/vendors/fontawesome5/css/all.min.css" rel="stylesheet" type="text/css" />
		<!--end:: Global Optional Vendors -->

		<!--begin::Global Theme Styles -->
		<link href="./assets/demo/base/style.bundle.css" rel="stylesheet" type="text/css" />
		<!--end::Global Theme Styles -->

		<link rel="shortcut icon" href="./assets/demo/media/img/logo/favicon.ico" />
		<link href="css/important.css" rel="stylesheet" type="text/css" />
	</head>

	<!-- end::Head -->

	<!-- begin::Body -->
	<body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">

		<!-- begin:: Page -->
		<div class="m-grid m-grid--hor m-grid--root m-page">
<!--			<div class="m-login m-login--signin  m-login--5" id="m_login" style="background-image: url(./assets/app/media/img//bg/bg-3.jpg);">-->
            <div class="m-login m-login--signin  m-login--5" id="m_login">
				<div class="m-login__wrapper-1 m-portlet-full-height">
					<div class="m-login__wrapper-1-1">
						<div class="m-login__contanier">
							<div class="m-login__content">
								<div class="m-login__logo">
									<a href="#">
										<img src="./assets/app/media/img/logos/logo-2.png">
									</a>
								</div>
								<div class="m-login__title">
									<h3 style="text-transform: uppercase"><?= $t->{'Junte-se à maior plataforma de pregão eletrônico do Brasil'}; ?></h3>
								</div>
								<div class="m-login__desc">
									<?= $t->{'Comprando ou vendendo, aqui você poupa dinheiro e tempo'}; ?>
								</div>
								<div class="m-login__form-action">
									<button type="button" id="m_login_signup" class="btn btn-outline-primary m-btn--pill"><?= $t->{'Ainda não tem uma conta?'}; ?></button>
								</div>
							</div>
						</div>
						<div class="m-login__border">
							<div></div>
						</div>
					</div>
				</div>
				<div class="m-login__wrapper-2 m-portlet-full-height">
					<div class="m-login__contanier">
						<div class="m-login__signin">
							<div class="m-login__head">
								<h3 class="m-login__title" style="text-transform: uppercase"><?= $t->{'Entre com suas credenciais'}; ?></h3>
							</div>
							<form class="m-login__form m-form" id="form-signin">
                                <input type="hidden" name="type" value="sign-in">
								<div class="form-group m-form__group">
									<input class="form-control m-input" type="text" placeholder="<?= $t->{'Nome de usuário'}; ?>" name="username" id="username" autocomplete="off">
								</div>
								<div class="form-group m-form__group">
									<input class="form-control m-input m-login__form-input--last" type="Password" placeholder="<?= $t->{'Senha'}; ?>" id="password" name="password">
								</div>
								<div class="row m-login__form-sub">
									<!--<div class="col m--align-left">
										<label class="m-checkbox m-checkbox--primary">
											<input type="checkbox" name="remember"> <?/*= $t->{'Lembrar de mim'}; */?>
											<span></span>
										</label>
									</div>-->
									<div class="col m--align-right">
										<a href="javascript:;" id="m_login_forget_password" class="m-link"><?= $t->{'Esqueceu a senha?'}; ?></a>
									</div>
								</div>
								<div class="m-login__form-action">
									<button id="m_login_signin_submit" class="btn btn-primary m-btn m-btn--pill m-btn--custom m-btn--air"><?= $t->{'Entrar'}; ?></button>
								</div>
							</form>
						</div>
						<div class="m-login__signup">
							<div class="m-login__head">
								<h3 class="m-login__title"><?= $t->{'Cadastrar'}; ?></h3>
								<div class="m-login__desc"><?= $t->{'Preencha os dados abaixo para iniciar o processo de criação de nova conta'}; ?></div>
							</div>
							<form class="m-login__form m-form" id="form-signup">
                                <input type="hidden" name="type" value="sign-up">
                                <div class="m-form__group form-group" style="text-align: center; border: 1px solid #ebedf2; padding-top: 1.0em; padding-bottom: 1.4em; border-radius: 6px;margin-bottom: 20px">
                                    <h5 style="padding: 10px"><?= $t->{'Tipo de cadastro'}; ?></h5>
                                    <div class="m-radio-inline">
                                        <label class="m-radio">
                                            <input type="radio" name="registry" id="registry_fisical_person" value="1"> <?= $t->{'Pessoa Física'}; ?>
                                            <span></span>
                                        </label>
                                        <label class="m-radio">
                                            <input type="radio" name="registry" id="registry_legal_person" value="2"> <?= $t->{'Pessoa Jurídica'}; ?>
                                            <span></span>
                                        </label>
                                    </div>
                                </div>
								<div class="form-group m-form__group">
									<input class="form-control m-input" type="text" placeholder="<?= $t->{'Nome de usuário'}; ?>" name="username">
								</div>
								<div class="form-group m-form__group">
									<input class="form-control m-input" type="text" placeholder="<?= $t->{'E-mail'}; ?>" name="email" autocomplete="off">
								</div>
								<div class="form-group m-form__group">
									<input class="form-control m-input" type="password" placeholder="<?= $t->{'Senha'}; ?>" id="password-signup" name="password">
								</div>
								<div class="form-group m-form__group">
									<input class="form-control m-input m-login__form-input--last" type="password" placeholder="<?= $t->{'Confirmação de senha'}; ?>" name="rpassword">
								</div>
                                <div class="m-separator m-separator--dashed"></div>
                                <div class="m-form__section">
                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title">Você é</h3>
                                    </div>
                                    <div class="form-group m-form__group">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <label class="m-option">
																<span class="m-option__control">
																	<span class="m-radio m-radio--state-success">
																		<input type="radio" name="role" value="customer" id="role_customer">
																		<span></span>
																	</span>
																</span>
                                                    <span class="m-option__label">
																	<span class="m-option__head">
																		<span class="m-option__title">
																			<?= $t->{'Cliente'}; ?>
																		</span>
																	</span>
																	<span class="m-option__body">
																		Deseja contratar o serviço para instalação de sua usina solar
																	</span>
																</span>
                                                </label>
                                            </div>
                                            <div class="col-lg-6">
                                                <label class="m-option">
																<span class="m-option__control">
																	<span class="m-radio m-radio--state-danger">
																		<input type="radio" name="role" value="provider" id="role_provider">
																		<span></span>
																	</span>
																</span>
                                                    <span class="m-option__label">
																	<span class="m-option__head">
																		<span class="m-option__title">
																			<?= $t->{'Integrador'}; ?>
																		</span>
																	</span>
																	<span class="m-option__body">
																		Faz a instalação de usinas solares para clientes residenciais e comerciais
																	</span>
																</span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="m-form__help">

                                        </div>
                                    </div>
                                </div>
                                <div class="m-separator m-separator--dashed"></div>
								<div class="m-login__form-sub">
									<label class="m-checkbox m-checkbox--primary">
										<input type="checkbox" name="agree"><?= $t->{'Eu concordo com os '}; ?> <a href="#" class="m-link m-link--primary"><?= $t->{'Termos de uso'}; ?></a>.
										<span></span>
									</label>
									<span class="m-form__help"></span>
								</div>
								<div class="m-login__form-action">
									<button id="m_login_signup_submit" class="btn btn-primary m-btn m-btn--pill m-btn--custom m-btn--air"><?= $t->{'Cadastrar'}; ?></button>
									<button id="m_login_signup_cancel" class="btn btn-outline-primary m-btn m-btn--pill m-btn--custom"><?= $t->{'Cancelar'}; ?></button>
								</div>
							</form>
						</div>
						<div class="m-login__forget-password">
							<div class="m-login__head">
								<h3 class="m-login__title"><?= $t->{'Esqueceu a senha?'}; ?></h3>
								<div class="m-login__desc"><?= $t->{'Coloque seu e-mail para receber as instruções sobre a troca de senha'}; ?></div>
							</div>
							<form class="m-login__form m-form" id="form-forgotpassword">
                                <input type="hidden" name="type" value="forgot-password">
								<div class="form-group m-form__group">
									<input class="form-control m-input" type="text" placeholder="E-mail" name="email" id="m_email" autocomplete="off">
								</div>
								<div class="m-login__form-action">
									<button id="m_login_forget_password_submit" class="btn btn-primary m-btn m-btn--pill m-btn--custom m-btn--air"><?= $t->{'Redefinir'}; ?></button>
									<button id="m_login_forget_password_cancel" class="btn btn-outline-primary m-btn m-btn--pill m-btn--custom "><?= $t->{'Cancelar'}; ?></button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end:: Page -->

		<!--begin:: Global Mandatory Vendors -->
		<script src="./assets/vendors/jquery/dist/jquery.js" type="text/javascript"></script>
		<script src="./assets/vendors/popper.js/dist/umd/popper.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/js-cookie/src/js.cookie.js" type="text/javascript"></script>
		<script src="./assets/vendors/moment/min/moment.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/tooltip.js/dist/umd/tooltip.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
		<script src="./assets/vendors/wnumb/wNumb.js" type="text/javascript"></script>
		<!--end:: Global Mandatory Vendors -->

		<!--begin:: Global Optional Vendors -->
		<script src="./assets/vendors/jquery.repeater/src/lib.js" type="text/javascript"></script>
		<script src="./assets/vendors/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
		<script src="./assets/vendors/jquery.repeater/src/repeater.js" type="text/javascript"></script>
		<script src="./assets/vendors/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/block-ui/jquery.blockUI.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-datepicker.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-timepicker.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-daterangepicker.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-switch.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
		<script src="./assets/vendors/select2/dist/js/select2.full.js" type="text/javascript"></script>
		<script src="./assets/vendors/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
		<script src="./assets/vendors/handlebars/dist/handlebars.js" type="text/javascript"></script>
		<script src="./assets/vendors/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
		<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
		<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.phone.extensions.js" type="text/javascript"></script>
		<script src="./assets/vendors/nouislider/distribute/nouislider.js" type="text/javascript"></script>
		<script src="./assets/vendors/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
		<script src="./assets/vendors/autosize/dist/autosize.js" type="text/javascript"></script>
		<script src="./assets/vendors/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
		<script src="./assets/vendors/dropzone/dist/dropzone.js" type="text/javascript"></script>
		<script src="./assets/vendors/summernote/dist/summernote.js" type="text/javascript"></script>
		<script src="./assets/vendors/markdown/lib/markdown.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-markdown.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
		<script src="./assets/vendors/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/forms/jquery-validation.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/base/bootstrap-notify.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/toastr/build/toastr.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/jstree/dist/jstree.js" type="text/javascript"></script>
		<script src="./assets/vendors/raphael/raphael.js" type="text/javascript"></script>
		<script src="./assets/vendors/morris.js/morris.js" type="text/javascript"></script>
		<script src="./assets/vendors/chartist/dist/chartist.js" type="text/javascript"></script>
		<script src="./assets/vendors/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/charts/chart.init.js" type="text/javascript"></script>
		<script src="./assets/vendors/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/vendors/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
		<script src="./assets/vendors/counterup/jquery.counterup.js" type="text/javascript"></script>
		<script src="./assets/vendors/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
		<script src="./assets/vendors/js/framework/components/plugins/base/sweetalert2.init.js" type="text/javascript"></script>
		<!--end:: Global Optional Vendors -->

		<script src="./assets/demo/base/scripts.bundle.js" type="text/javascript"></script>
        <script src="./assets/demo/custom/crud/forms/widgets/bootstrap-switch.js" type="text/javascript"></script>

	</body>

	<!-- end::Body -->
</html>
<script>

    $('#m_login input[name=registry]').click(function() {
        if ($('#registry_fisical_person').is(':checked')){
            console.log("tava checado");
            $('#role_provider').prop("disabled", true);
            $('#role_provider').prop("checked", false);

        }else{
            console.log("não tava checado");
            $('#role_provider').prop("disabled", false);
        }
    });


//== Class Definition
var SnippetLogin = function() {

    var login = $('#m_login');

    var showMsg = function(form, type, msg) {
        var alert = $('<div class="m-alert m-alert--outline alert alert-' + type + ' alert-dismissible" role="alert">\ <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>\ <span></span>\ </div>');

        form.find('.alert').remove();
        alert.prependTo(form);
        //alert.animateClass('fadeIn animated');
        mUtil.animateClass(alert[0], 'fadeIn animated');
        alert.find('span').html(msg);
    }

    //== Private Functions

    var displaySignUpForm = function() {
        login.removeClass('m-login--forget-password');
        login.removeClass('m-login--signin');

        login.addClass('m-login--signup');
        mUtil.animateClass(login.find('.m-login__signup')[0], 'flipInX animated');
    }

    var displaySignInForm = function() {
        login.removeClass('m-login--forget-password');
        login.removeClass('m-login--signup');

        login.addClass('m-login--signin');
        mUtil.animateClass(login.find('.m-login__signin')[0], 'flipInX animated');
        //login.find('.m-login__signin').animateClass('flipInX animated');
    }

    var displayForgetPasswordForm = function() {
        login.removeClass('m-login--signin');
        login.removeClass('m-login--signup');

        login.addClass('m-login--forget-password');
        //login.find('.m-login__forget-password').animateClass('flipInX animated');
        mUtil.animateClass(login.find('.m-login__forget-password')[0], 'flipInX animated');

    }

    var handleFormSwitch = function() {
        $('#m_login_forget_password').click(function(e) {
            e.preventDefault();
            displayForgetPasswordForm();
        });

        $('#m_login_forget_password_cancel').click(function(e) {
            e.preventDefault();
            displaySignInForm();
        });

        $('#m_login_signup').click(function(e) {
            e.preventDefault();
            displaySignUpForm();
        });

        $('#m_login_signup_cancel').click(function(e) {
            e.preventDefault();
            displaySignInForm();
        });
    }

    var handleSignInFormSubmit = function() {
        $('#m_login_signin_submit').click(function(e) {
            e.preventDefault();
            var btn = $(this);
            var form = $(this).closest('form');

            form.validate({
                rules: {
                    username: {
                        required: true,
                    },
                    password: {
                        required: true
                    }
                },
                messages: {
                    username: "Informe o nome de usuário",
                    password: "Insira sua senha"
                }
            });

            if (!form.valid()) {
                return;
            }

            btn.addClass('m-loader m-loader--right m-loader--light').attr('disabled', true);

            form.ajaxSubmit({
                url: './actions/login.php',
                type: 'POST',
                contentType: "application/x-www-form-urlencoded",
                data: $('#form-signin').serialize(),
                success: function(response, status, xhr, $form) {

                    if (response.status == 1) {

                        btn.attr('disabled', true);
                        showMsg(form, 'success', response.description);

                        setTimeout(function() {

                            //reset button to original state
                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 2000);

                    } else {
                        setTimeout(function() {

                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);
                            showMsg(form, 'danger', response.description);

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 2000);
                    }
                }
            });
        });
    }

    var handleSignUpFormSubmit = function() {
        $('#m_login_signup_submit').click(function(e) {
            e.preventDefault();

            var btn = $(this);
            var form = $(this).closest('form');

            form.validate({
                rules: {
                    registry: {
                        required: true
                    },
                    username: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    password: {
                        required: true
                    },
                    rpassword: {
                        required: true,
                        equalTo : '#password-signup'
                    },
                    role: {
                        required: true
                    },
                    agree: {
                        required: true
                    }
                },
                messages: {
                    registry: "Informe o tipo de cadastro",
                    username: "Informe o nome de usuário",
                    email: "Verifique o campo de e-mail",
                    password: "Escolha uma uma senha",
                    rpassword: "A confirmação de senha deve ser igual ao campo senha",
                    role: "Selecione o tipo de usuário",
                    agree: "É necessário aceitar os Termos de Uso para efetuar o cadastro no site"
                }
            });

            if (!form.valid()) {
                return;
            }

            btn.addClass('m-loader m-loader--right m-loader--light').attr('disabled', true);

            form.ajaxSubmit({
                url: './actions/login.php',
                type: 'POST',
                contentType: "application/x-www-form-urlencoded",
                data: $('#form-signup').serialize(),
                success: function(response, status, xhr, $form) {

                    if (response.status == 1) {

                        btn.attr('disabled', true);
                        showMsg(form, response.type, response.description);

                        setTimeout(function() {

                            //reset button to original state
                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);

                            // display signup form
                            displaySignInForm();
                            var signInForm = login.find('.m-login__signin form');
                            signInForm.clearForm();
                            signInForm.validate().resetForm();

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 3000);

                    } else {
                        setTimeout(function() {

                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);
                            showMsg(form, response.type, response.description);

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 2000);
                    }

                }
            });
        });
    }

    var handleForgetPasswordFormSubmit = function() {
        $('#m_login_forget_password_submit').click(function(e) {
            e.preventDefault();

            var btn = $(this);
            var form = $(this).closest('form');

            form.validate({
                rules: {
                    email: {
                        required: true,
                        email: true
                    }
                },
                messages: {
                    email: "Verifique o campo de e-mail",
                }
            });

            if (!form.valid()) {
                return;
            }

            btn.addClass('m-loader m-loader--right m-loader--light').attr('disabled', true);

            form.ajaxSubmit({
                url: './actions/login.php',
                type: 'POST',
                contentType: "application/x-www-form-urlencoded",
                data: $('#form-forgotpassword').serialize(),
                success: function(response, status, xhr, $form) {

                    if (response.status == 1) {

                        btn.attr('disabled', true);
                        showMsg(form, 'success', response.description);
                        form.clearForm();
                        form.validate().resetForm();

                        setTimeout(function() {

                            //reset button to original state
                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);

                            // display signup form
                            displaySignInForm();
                            var signInForm = login.find('.m-login__signin form');
                            signInForm.clearForm();
                            signInForm.validate().resetForm();

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 2000);

                    } else {
                        setTimeout(function() {

                            btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);
                            showMsg(form, 'danger', response.description);

                            if (response.route != null) {
                                location.href = response.route;
                            }

                        }, 2000);
                    }

                }
            });
        });
    }

    //== Public Functions
    return {
        // public functions
        init: function() {
            handleFormSwitch();
            handleSignInFormSubmit();
            handleSignUpFormSubmit();
            handleForgetPasswordFormSubmit();
        }
    };
}();

var UserAccountValidation = function() {

    var sendUserAccountActivateParameter = function() {

        var searchParams = new URLSearchParams(window.location.search);
        var accountActivate;

        if (searchParams.has('account-activate')){
            accountActivate = searchParams.get('account-activate');
        }

        if (accountActivate == null){
            return;
        }

        $.ajax({
            url: './actions/login.php',
            type: 'POST',
            contentType: "application/x-www-form-urlencoded",
            data: {"account-activate" : accountActivate},
            success: function(response, status, xhr) {

                if (response.status == 1) {
                    //deu certo
                    toastr[response.type](response.description);

                    if (response.route != null) {
                        location.href = response.route;
                    }

                } else {
                    //deu errado
                    toastr[response.type](response.description);

                    if (response.route != null) {
                        location.href = response.route;
                    }

                }

            }
        });

    }

    return {
        // public functions
        init: function() {
            sendUserAccountActivateParameter();
        }
    };

}();

//== Class Initialization
jQuery(document).ready(function() {
    UserAccountValidation.init();
    SnippetLogin.init();
});

</script>