<?php
    ### VALIDATE SESSION
    session_start();

    ### INCLUDE
    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/models/User.php";
    require_once "$root/panel/internationalization/Translate.php";
    require_once "$root/panel/models/LegalPerson.php";
    require_once "$root/panel/models/FisicalPerson.php";

    ### BODY PAGE CONSTRUCT
    require_once "$root/panel/body/header.phtml";
    $file = $_GET["page"].".phtml";
    $fileExists = file_exists($file);
    if ($fileExists == true) { include($file); }else{ print("<meta http-equiv='refresh' content='0;url=404'>"); }
    require_once "$root/panel/body/footer.phtml";
?>