<?php
    session_start();

    if ($_SESSION == null) { header('Location: ./login'); }

    ### INCLUDE
    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/body/header.phtml";
    require_once "$root/panel/models/User.php";
    require_once "$root/panel/internationalization/Translate.php";

    $fileExists = file_exists($_GET["page"].".phtml");

    if ($fileExists == true) {
      //carrega página que veio no get
      include($_GET["page"].".phtml"); //views são sempre PHTML
    }else{
      //exibe erro 404
      print("<meta http-equiv='refresh' content='0;url=404'>");
    }

    include("./body/footer.phtml");
?>
