<?php

  session_start();

  include("./body/header.phtml");

  $fileExists = file_exists($_GET["page"].".phtml");

  if ($fileExists == true) {
    //carrega página que veio no get
    include($_GET["page"].".phtml"); //views são sempre PHTML
  }else{
    //exibe erro 404
    print("<meta http-equiv='refresh' content='0;url=404'>");
  }

  include("./body/footer.phtml");

  //pegar variáveis e fazer chamadas para popular logs e outras funcionalidades

?>
