<?php

    ### USER SESSION
    $user = unserialize($_SESSION['USER']);
    $fisicalPerson = unserialize($_SESSION['FISICAL_PERSON']);
    $legalPerson = unserialize($_SESSION['LEGAL_PERSON']);

    ### PAGE STRUCTURE SESSION VARS
    $_SESSION['top-menu-admin'] = $user->role_id == 1 ? true : false;
    $_SESSION['top-quick-search'] = false;
    $_SESSION['top-notifications'] = false;
    $_SESSION['top-quick-actions'] = false;
    $_SESSION['top-profile'] = false;
    $_SESSION['top-quick-sidebar'] = false;
    $_SESSION['menu-left'] = false;

    $t = new Translate();

?>
<div class="m-portlet m-portlet--full-height col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <!--begin: Portlet Head-->
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    <?=$t->{"Cadastro de pessoa física"}?>
                    <small><?=$t->{"Siga os passos abaixo"}?></small>
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="#" data-toggle="m-tooltip" class="m-portlet__nav-link m-portlet__nav-link--icon" data-direction="left" data-width="auto" title="Get help with filling up this form">
                        <i class="flaticon-info m--icon-font-size-lg3"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!--end: Portlet Head-->

    <!--begin: Form Wizard-->
    <div class="m-wizard m-wizard--2 m-wizard--success" id="m_wizard">

        <!--begin: Message container -->
        <div class="m-portlet__padding-x">

            <!-- Here you can put a message or alert -->
        </div>

        <!--end: Message container -->

        <!--begin: Form Wizard Head -->
        <div class="m-wizard__head m-portlet__padding-x">

            <!--begin: Form Wizard Progress -->
            <div class="m-wizard__progress">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>

            <!--end: Form Wizard Progress -->

            <!--begin: Form Wizard Nav -->
            <div class="m-wizard__nav">
                <div class="m-wizard__steps">
                    <div class="m-wizard__step m-wizard__step--current" m-wizard-target="m_wizard_form_step_1">
                        <a href="#" class="m-wizard__step-number">
                            <span><i class="fa  flaticon-user"></i></span>
                        </a>
                        <div class="m-wizard__step-info">
                            <div class="m-wizard__step-title">
                                1. <?=$t->{"Informações pessoais"}?>
                            </div>
                            <div class="m-wizard__step-desc">
                                <?=$t->{"Dados pessoais e <br>de contato"}?>
                            </div>
                        </div>
                    </div>
                    <div class="m-wizard__step" m-wizard-target="m_wizard_form_step_2">
                        <a href="#" class="m-wizard__step-number">
                            <span><i class="fa  flaticon-placeholder"></i></span>
                        </a>
                        <div class="m-wizard__step-info">
                            <div class="m-wizard__step-title">
                                2. <?=$t->{"Dados de endereço"}?>
                            </div>
                            <div class="m-wizard__step-desc">
                                <?=$t->{"Dados <br>de sua localização"}?>
                            </div>
                        </div>
                    </div>
                        <div class="m-wizard__step" m-wizard-target="m_wizard_form_step_3">
                            <a href="#" class="m-wizard__step-number">
                                <span><i class="fa  flaticon-layers"></i></span>
                            </a>
                            <div class="m-wizard__step-info">
                                <div class="m-wizard__step-title">
                                    3. <?=$t->{"Confirmação"}?>
                                </div>
                                <div class="m-wizard__step-desc">
                                    <?=$t->{"Termos de uso <br>e confirmação"}?>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>

            <!--end: Form Wizard Nav -->
        </div>

        <!--end: Form Wizard Head -->

        <!--begin: Form Wizard Form-->
        <div class="m-wizard__form">

            <form class="m-form m-form--label-align-left- m-form--state-" id="m_form">

                <!--begin: Form Body -->
                <div class="m-portlet__body">

                    <!--begin: Form Wizard Step 1-->
                    <div class="m-wizard__form-step m-wizard__form-step--current" id="m_wizard_form_step_1">
                        <div class="row">
                            <div class="col-xl-8 offset-xl-2">
                                <div class="m-form__section m-form__section--first">
                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title"><?=$t->{"Dados pessoais"}?></h3>
                                    </div>
                                    <div class="form-group m-form__group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label"><?=$t->{"Nome completo"}?>: *</label>
                                        <div class="col-xl-9 col-lg-9">
                                            <input type="text" name="name" class="form-control m-input" placeholder="<?=$t->{"John Doe"}?>" value="">
                                            <span class="m-form__help"><?=$t->{"Coloque seu nome completo, sem omitir ou abreviar nenhum nome"}?></span>
                                        </div>
                                    </div>
                                    <div class="form-group m-form__group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label"><?=$t->{"Como prefere ser chamado"}?>: *</label>
                                        <div class="col-xl-9 col-lg-9">
                                            <input type="text" name="name" class="form-control m-input" placeholder="<?=$t->{"John"}?>" value="">
                                            <span class="m-form__help"><?=$t->{"Primeiro nome, sobrenome, nome composto ou apelido"}?></span>
                                        </div>
                                    </div>

                                </div>
                                <div class="m-separator m-separator--dashed m-separator--lg"></div>
                                <div class="m-form__section">
                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title">
                                            Contato
<!--                                            <i data-toggle="m-tooltip" data-width="auto" class="m-form__heading-help-icon flaticon-info" title="Some help text goes here"></i>-->
                                        </h3>
                                    </div>
                                    <div class="form-group m-form__group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label"><?=$t->{"Telefone celular"}?>: *</label>
                                        <div class="col-xl-9 col-lg-9">
                                            <div class="input-group">
                                                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-phone"></i></span></div>
                                                <input type="text" name="phone" class="form-control m-input" placeholder="<?=$t->{"(××)×××××-××××"}?>" value="">
                                            </div>
                                            <span class="m-form__help"><?=$t->{"Coloque o seu telefone no formato válido para o Brasil (××)×××××-××××"}?></span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Step 1-->

                    <!--begin: Form Wizard Step 2-->
                    <div class="m-wizard__form-step" id="m_wizard_form_step_2">
                        <div class="row">
                            <div class="col-xl-8 offset-xl-2">
                                <div class="m-form__section m-form__section--first">
                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title"><?=$t->{"Endereço"}?></h3>
                                    </div>
                                    <div class="form-group m-form__group row">
                                        <div class="col-lg-12">
                                            <label class="form-control-label"><?=$t->{"Rua / Avenida"}?>: *</label>
                                            <input type="url" name="account_url" class="form-control m-input" placeholder="<?=$t->{"Ex: Rua Araguari"}?>" value="">
                                            <span class="m-form__help">Please enter your preferred URL to your dashboard</span>
                                        </div>
                                    </div>
                                    <div class="form-group m-form__group row">
                                        <div class="col-lg-6 m-form__group-sub">
                                            <label class="form-control-label">* Username:</label>
                                            <input type="text" name="account_username" class="form-control m-input" placeholder="" value="nick.stone">
                                            <span class="m-form__help">Your username to login to your dashboard</span>
                                        </div>
                                        <div class="col-lg-6 m-form__group-sub">
                                            <label class="form-control-label">* Password:</label>
                                            <input type="password" name="account_password" class="form-control m-input" placeholder="" value="qwerty">
                                            <span class="m-form__help">Please use letters and at least one number and symbol</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Step 2-->

                    <!--begin: Form Wizard Step 3-->
                    <div class="m-wizard__form-step" id="m_wizard_form_step_3">
                        <div class="row">
                            <div class="col-xl-8 offset-xl-2">

                                <!--begin::Section-->
                                <ul class="nav nav-tabs m-tabs-line--2x m-tabs-line m-tabs-line--danger" role="tablist">
                                    <li class="nav-item m-tabs__item">
                                        <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_form_confirm_1" role="tab">1. Client Information</a>
                                    </li>
                                    <li class="nav-item m-tabs__item">
                                        <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_form_confirm_2" role="tab">2. Account Setup</a>
                                    </li>
                                    <li class="nav-item m-tabs__item">
                                        <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_form_confirm_3" role="tab">3. Billing Setup</a>
                                    </li>
                                </ul>
                                <div class="tab-content m--margin-top-40">
                                    <div class="tab-pane active" id="m_form_confirm_1" role="tabpanel">
                                        <div class="m-form__section m-form__section--first">
                                            <div class="m-form__heading">
                                                <h4 class="m-form__heading-title">Client Details</h4>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Name:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">Nick Stone</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Email:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">nick.stone@gmail.com</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Phone</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">+206-78-55034890</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="m-separator m-separator--dashed m-separator--lg"></div>
                                        <div class="m-form__section">
                                            <div class="m-form__heading">
                                                <h4 class="m-form__heading-title">Corresponding Address <i data-toggle="m-tooltip" data-width="auto" class="m-form__heading-help-icon flaticon-info" title="Some help text goes here"></i></h4>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Address Line 1:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">Headquarters 1120 N Street Sacramento 916-654-5266</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Address Line 2:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">P.O. Box 942873 Sacramento, CA 94273-0001</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">City:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">Polo Alto</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">State:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">California</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Country:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">USA</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="m_form_confirm_2" role="tabpanel">
                                        <div class="m-form__section m-form__section--first">
                                            <div class="m-form__heading">
                                                <h4 class="m-form__heading-title">Account Details</h4>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">URL:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">sinortech.vertoffice.com</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Username:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">sinortech.admin</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Password:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">*********</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="m-separator m-separator--dashed m-separator--lg"></div>
                                        <div class="m-form__section">
                                            <div class="m-form__heading">
                                                <h4 class="m-form__heading-title">Account Details</h4>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">URL:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">sinortech.vertoffice.com</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Username:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">sinortech.admin</span>
                                                </div>
                                            </div>
                                            <div class="form-group m-form__group m-form__group--sm row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">Password:</label>
                                                <div class="col-xl-9 col-lg-9">
                                                    <span class="m-form__control-static">*********</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="m_form_confirm_3" role="tabpanel">
                                        <div class="m-form__section m-form__section--first">
                                            <div class="m-form__section">
                                                <div class="m-form__heading">
                                                    <h4 class="m-form__heading-title">Client Settings</h4>
                                                </div>
                                                <div class="form-group m-form__group m-form__group--sm row">
                                                    <label class="col-xl-3 col-lg-3 col-form-label">User Group:</label>
                                                    <div class="col-xl-9 col-lg-9">
                                                        <span class="m-form__control-static">Customer</span>
                                                    </div>
                                                </div>
                                                <div class="form-group m-form__group m-form__group--sm row">
                                                    <label class="col-xl-3 col-lg-3 col-form-label">Communications:</label>
                                                    <div class="col-xl-9 col-lg-9">
                                                        <span class="m-form__control-static">Phone, Email</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!--end::Section-->

                                <!--end::Section-->
                                <div class="m-separator m-separator--dashed m-separator--lg"></div>
                                <div class="form-group m-form__group m-form__group--sm row">
                                    <div class="col-xl-12">
                                        <div class="m-checkbox-inline">
                                            <label class="m-checkbox m-checkbox--solid m-checkbox--brand">
                                                <input type="checkbox" name="accept" value="1">
                                                Click here to indicate that you have read and agree to the terms presented in the Terms and Conditions agreement
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Step 3-->
                </div>

                <!--end: Form Body -->

                <!--begin: Form Actions -->
                <div class="m-portlet__foot m-portlet__foot--fit m--margin-top-40">
                    <div class="m-form__actions">
                        <div class="row">
                            <div class="col-lg-2"></div>
                            <div class="col-lg-4 m--align-left">
                                <a href="#" class="btn btn-secondary m-btn m-btn--custom m-btn--icon" data-wizard-action="prev">
															<span>
																<i class="la la-arrow-left"></i>&nbsp;&nbsp;
																<span>Back</span>
															</span>
                                </a>
                            </div>
                            <div class="col-lg-4 m--align-right">
                                <a href="#" class="btn btn-primary m-btn m-btn--custom m-btn--icon" data-wizard-action="submit">
															<span>
																<i class="la la-check"></i>&nbsp;&nbsp;
																<span>Submit</span>
															</span>
                                </a>
                                <a href="#" class="btn btn-warning m-btn m-btn--custom m-btn--icon" data-wizard-action="next">
															<span>
																<span>Save & Continue</span>&nbsp;&nbsp;
																<i class="la la-arrow-right"></i>
															</span>
                                </a>
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                    </div>
                </div>

                <!--end: Form Actions -->
            </form>
        </div>

        <!--end: Form Wizard Form-->
    </div>

    <!--end: Form Wizard-->
</div>
<script>
var WizardDemo = function () {
    //== Base elements
    var wizardEl = $('#m_wizard');
    var formEl = $('#m_form');
    var validator;
    var wizard;

    //== Private functions
    var initWizard = function () {
        //== Initialize form wizard
        wizard = new mWizard('m_wizard', {
            startStep: 1
        });

        //== Validation before going to next page
        wizard.on('beforeNext', function(wizard) {
            if (validator.form() !== true) {
                wizard.stop();  // don't go to the next step
            }
        })

        //== Change event
        wizard.on('change', function(wizard) {
            mUtil.scrollTop();
        });
    }

    var initValidation = function() {
        validator = formEl.validate({
            //== Validate only visible fields
            ignore: ":hidden",

            //== Validation rules
            rules: {
                //=== Client Information(step 1)
                //== Client details
                name: {
                    required: false
                },
                email: {
                    required: true,
                    email: true
                },
                phone: {
                    required: false,
                    phoneUS: false
                },

                //== Mailing address
                address1: {
                    required: true
                },
                city: {
                    required: true
                },
                state: {
                    required: true
                },
                city: {
                    required: true
                },
                country: {
                    required: true
                },

                //=== Client Information(step 2)
                //== Account Details
                account_url: {
                    required: true,
                    url: true
                },
                account_username: {
                    required: true,
                    minlength: 4
                },
                account_password: {
                    required: true,
                    minlength: 6
                },

                //== Client Settings
                account_group: {
                     required: true
                },
                'account_communication[]': {
                    required: true
                },

                //=== Client Information(step 3)
                //== Billing Information
                billing_card_name: {
                    required: true
                },
                billing_card_number: {
                    required: true,
                    creditcard: true
                },
                billing_card_exp_month: {
                    required: true
                },
                billing_card_exp_year: {
                    required: true
                },
                billing_card_cvv: {
                    required: true,
                    minlength: 2,
                    maxlength: 3
                },

                //== Billing Address
                billing_address_1: {
                    required: true
                },
                billing_address_2: {

                },
                billing_city: {
                    required: true
                },
                billing_state: {
                    required: true
                },
                billing_zip: {
                    required: true,
                    number: true
                },
                billing_delivery: {
                    required: true
                },

                //=== Confirmation(step 4)
                accept: {
                    required: true
                }
            },

            //== Validation messages
            messages: {
                'account_communication[]': {
                    required: 'You must select at least one communication option'
                },
                accept: {
                    required: "You must accept the Terms and Conditions agreement!"
                }
            },

            //== Display error
            invalidHandler: function(event, validator) {
                mUtil.scrollTop();

                swal({
                    "title": "",
                    "text": "There are some errors in your submission. Please correct them.",
                    "type": "error",
                    "confirmButtonClass": "btn btn-secondary m-btn m-btn--wide"
                });
            },

            //== Submit valid form
            submitHandler: function (form) {

            }
        });
    }

    var initSubmit = function() {
        var btn = formEl.find('[data-wizard-action="submit"]');

        btn.on('click', function(e) {
            e.preventDefault();

            if (validator.form()) {
                //== See: src\js\framework\base\app.js
                mApp.progress(btn);
                //mApp.block(formEl);

                //== See: http://malsup.com/jquery/form/#ajaxSubmit
                formEl.ajaxSubmit({
                    success: function() {
                        mApp.unprogress(btn);
                        //mApp.unblock(formEl);

                        swal({
                            "title": "",
                            "text": "The application has been successfully submitted!",
                            "type": "success",
                            "confirmButtonClass": "btn btn-secondary m-btn m-btn--wide"
                        });
                    }
                });
            }
        });
    }

    return {
        // public functions
        init: function() {
            wizardEl = $('#m_wizard');
            formEl = $('#m_form');

            initWizard();
            initValidation();
            initSubmit();
        }
    };
}();

jQuery(document).ready(function() {
    WizardDemo.init();
});
</script>