</div>

<!-- end:: Body -->

<!-- begin::Footer -->
<footer class="m-grid__item		m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
							<span class="m-footer__copyright">
								<?=date("Y"); ?> &copy; Solarbid'
							</span>
            </div>
            <div class="m-stack__item m-stack__item--righm-nav-stickyt m-stack__item--middle m-stack__item--first">
                <ul class="m-footer__nav m-nav m-nav--inline m--pull-right">
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">FAQ</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Política de privacidade</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Sobre</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Documentação</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- end::Footer -->
</div>

<!-- end:: Page -->

<!-- begin::Quick Sidebar -->
<div id="m_quick_sidebar" class="m-quick-sidebar m-quick-sidebar--tabbed m-quick-sidebar--skin-light">
    <div class="m-quick-sidebar__content m--hide">
        <span id="m_quick_sidebar_close" class="m-quick-sidebar__close"><i class="la la-close"></i></span>
        <ul id="m_quick_sidebar_tabs" class="nav nav-tabs m-tabs m-tabs-line m-tabs-line--brand" role="tablist">
<!--            --><?php
//            if (file_exists("./body/top-quick-sidebar-messages.phtml")) {
//              echo '<li class="nav-item m-tabs__item">
//                        <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_quick_sidebar_tabs_messenger" role="tab">Messages</a>
//                    </li>';
//            }?>


            <li class="nav-item m-tabs__item">
                <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_quick_sidebar_tabs_settings" role="tab">Settings</a>
            </li>
            <li class="nav-item m-tabs__item">
                <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_quick_sidebar_tabs_logs" role="tab">Logs</a>
            </li>
        </ul>
        <div class="tab-content">
            <?php
//            if (file_exists("./body/top-quick-sidebar-messages.phtml")) {
//                include("./body/top-quick-sidebar-messages.phtml");
//            }

            if (file_exists("./body/top-quick-sidebar-settings.phtml")) {
                include("./body/top-quick-sidebar-settings.phtml");
            }

            if (file_exists("./body/top-quick-sidebar-logs.phtml")) {
                include("./body/top-quick-sidebar-logs.phtml");
            }
            ?>


        </div>
    </div>
</div>

<!-- end::Quick Sidebar -->

<!-- begin::Scroll Top -->
<div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
</div>

<!-- end::Scroll Top -->

<!--begin:: Global Mandatory Vendors -->
<script src="./assets/vendors/jquery/dist/jquery.js" type="text/javascript"></script>
<script src="./assets/vendors/popper.js/dist/umd/popper.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="./assets/vendors/js-cookie/src/js.cookie.js" type="text/javascript"></script>
<script src="./assets/vendors/moment/min/moment.min.js" type="text/javascript"></script>
<script src="./assets/vendors/tooltip.js/dist/umd/tooltip.min.js" type="text/javascript"></script>
<script src="./assets/vendors/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
<script src="./assets/vendors/wnumb/wNumb.js" type="text/javascript"></script>

<!--end:: Global Mandatory Vendors -->

<!--begin:: Global Optional Vendors -->
<script src="./assets/vendors/jquery.repeater/src/lib.js" type="text/javascript"></script>
<script src="./assets/vendors/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
<script src="./assets/vendors/jquery.repeater/src/repeater.js" type="text/javascript"></script>
<script src="./assets/vendors/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
<script src="./assets/vendors/block-ui/jquery.blockUI.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-datepicker.init.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-timepicker.init.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-daterangepicker.init.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-switch.init.js" type="text/javascript"></script>
<script src="./assets/vendors/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
<script src="./assets/vendors/select2/dist/js/select2.full.js" type="text/javascript"></script>
<script src="./assets/vendors/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
<script src="./assets/vendors/handlebars/dist/handlebars.js" type="text/javascript"></script>
<script src="./assets/vendors/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
<script src="./assets/vendors/inputmask/dist/inputmask/inputmask.phone.extensions.js" type="text/javascript"></script>
<script src="./assets/vendors/nouislider/distribute/nouislider.js" type="text/javascript"></script>
<script src="./assets/vendors/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
<script src="./assets/vendors/autosize/dist/autosize.js" type="text/javascript"></script>
<script src="./assets/vendors/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
<script src="./assets/vendors/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
<script src="./assets/vendors/dropzone/dist/dropzone.js" type="text/javascript"></script>
<script src="./assets/vendors/summernote/dist/summernote.js" type="text/javascript"></script>
<script src="./assets/vendors/markdown/lib/markdown.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/bootstrap-markdown.init.js" type="text/javascript"></script>
<script src="./assets/vendors/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
<script src="./assets/vendors/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/forms/jquery-validation.init.js" type="text/javascript"></script>
<script src="./assets/vendors/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/base/bootstrap-notify.init.js" type="text/javascript"></script>
<script src="./assets/vendors/toastr/build/toastr.min.js" type="text/javascript"></script>
<script src="./assets/vendors/jstree/dist/jstree.js" type="text/javascript"></script>
<script src="./assets/vendors/raphael/raphael.js" type="text/javascript"></script>
<script src="./assets/vendors/morris.js/morris.js" type="text/javascript"></script>
<script src="./assets/vendors/chartist/dist/chartist.js" type="text/javascript"></script>
<script src="./assets/vendors/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/charts/chart.init.js" type="text/javascript"></script>
<script src="./assets/vendors/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
<script src="./assets/vendors/vendors/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
<script src="./assets/vendors/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
<script src="./assets/vendors/counterup/jquery.counterup.js" type="text/javascript"></script>
<script src="./assets/vendors/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
<script src="./assets/vendors/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
<script src="./assets/vendors/js/framework/components/plugins/base/sweetalert2.init.js" type="text/javascript"></script>

<!--end:: Global Optional Vendors -->

<!--begin::Global Theme Bundle -->
<script src="assets/demo/base/scripts.bundle.js" type="text/javascript"></script>

<!--end::Global Theme Bundle -->
</body>

<!-- end::Body -->
</html>
