<div class="tab-pane active" id="m_quick_sidebar_tabs_logs" role="tabpanel">
    <div class="m-list-timeline m-scrollable">
        <div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                System Logs
            </div>
            <div class="m-list-timeline__items">
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">12 new users registereda <span class="m-badge m-badge--warning m-badge--wide">important</span></a>
                    <span class="m-list-timeline__time">Just now</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">System shutdown</a>
                    <span class="m-list-timeline__time">11 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-danger"></span>
                    <a href="" class="m-list-timeline__text">New invoice received</a>
                    <span class="m-list-timeline__time">20 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-warning"></span>
                    <a href="" class="m-list-timeline__text">Database overloaded 89% <span class="m-badge m-badge--success m-badge--wide">resolved</span></a>
                    <span class="m-list-timeline__time">1 hr</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">System error</a>
                    <span class="m-list-timeline__time">2 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">Production server down <span class="m-badge m-badge--danger m-badge--wide">pending</span></a>
                    <span class="m-list-timeline__time">3 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">Production server up</a>
                    <span class="m-list-timeline__time">5 hrs</span>
                </div>
            </div>
        </div>
        <div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                Applications Logs
            </div>
            <div class="m-list-timeline__items">
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">New order received <span class="m-badge m-badge--info m-badge--wide">urgent</span></a>
                    <span class="m-list-timeline__time">7 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">12 new users registered</a>
                    <span class="m-list-timeline__time">Just now</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">System shutdown</a>
                    <span class="m-list-timeline__time">11 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-danger"></span>
                    <a href="" class="m-list-timeline__text">New invoices received</a>
                    <span class="m-list-timeline__time">20 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-warning"></span>
                    <a href="" class="m-list-timeline__text">Database overloaded 89%</a>
                    <span class="m-list-timeline__time">1 hr</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">System error <span class="m-badge m-badge--info m-badge--wide">pending</span></a>
                    <span class="m-list-timeline__time">2 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">Production server down</a>
                    <span class="m-list-timeline__time">3 hrs</span>
                </div>
            </div>
        </div>
        <div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                Server Logs
            </div>
            <div class="m-list-timeline__items">
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">Production server up</a>
                    <span class="m-list-timeline__time">5 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">New order received</a>
                    <span class="m-list-timeline__time">7 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">12 new users registered</a>
                    <span class="m-list-timeline__time">Just now</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">System shutdown</a>
                    <span class="m-list-timeline__time">11 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-danger"></span>
                    <a href="" class="m-list-timeline__text">New invoice received</a>
                    <span class="m-list-timeline__time">20 mins</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-warning"></span>
                    <a href="" class="m-list-timeline__text">Database overloaded 89%</a>
                    <span class="m-list-timeline__time">1 hr</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">System error</a>
                    <span class="m-list-timeline__time">2 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">Production server down</a>
                    <span class="m-list-timeline__time">3 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">Production server up</a>
                    <span class="m-list-timeline__time">5 hrs</span>
                </div>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-info"></span>
                    <a href="" class="m-list-timeline__text">New order received</a>
                    <span class="m-list-timeline__time">1117 hrs</span>
                </div>
            </div>
        </div>
    </div>
</div>