<div class="tab-pane" id="m_quick_sidebar_tabs_messenger" role="tabpanel">
    <div class="m-messenger m-messenger--message-arrow m-messenger--skin-light">
        <div class="m-messenger__messages m-scrollable">
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-pic">
                        <img src="assets/app/media/img//users/user3.jpg" alt="" />
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                User 1
                            </div>
                            <div class="m-messenger__message-text">
                                Message 1
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Message 2
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="m-messenger__seperator"></div>
        <div class="m-messenger__form">
            <div class="m-messenger__form-controls">
                <input type="text" name="" placeholder="Type here..." class="m-messenger__form-input">
            </div>
            <div class="m-messenger__form-tools">
                <a href="" class="m-messenger__form-attachment">
                    <i class="la la-paperclip"></i>
                </a>
            </div>
        </div>
    </div>
</div>