<?php

    ### INCLUDE
    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/internationalization/Translate.php";
    require_once "$root/panel/models/User.php";
    require_once "$root/panel/models/Notification.php";
    require_once "$root/panel/models/LogUser.php";

    $t = new Translate();

    $user = unserialize($_SESSION['USER']);
    $refreshedUser = User::getUserById($user->id);

    $newNotifications = Notification::all("is_read = '0' AND user_id = '$user->id' ORDER BY created_at DESC");
    $oldNotifications = Notification::all("is_read = '1' AND user_id = '$user->id' ORDER BY created_at DESC LIMIT 50");

    $userLogs = LogUser::all("user_id = '$user->id' ORDER BY created_at DESC LIMIT 50");
?>
<li class="m-nav__item m-topbar__notifications m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center 	m-dropdown--mobile-full-width" m-dropdown-toggle="click" m-dropdown-persistent="1">
    <a href="#" class="m-nav__link m-dropdown__toggle" id="m_topbar_notification_icon">
<span class="m-nav__link-icon">
<span class="m-nav__link-icon-wrapper"><i class="flaticon-alarm"></i></span>
<?php if(count($newNotifications) > 0) {?><span class="m-nav__link-badge m-badge m-badge--success"><?=count($newNotifications)?></span><?php } ?>
</span>
    </a>
    <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--center"></span>
        <div class="m-dropdown__inner">
            <?php if(count($newNotifications) > 0) {?><div class="m-dropdown__header m--align-center">
                <span class="m-dropdown__header-title"><?=count($newNotifications) ?> <?=count($newNotifications) == 1 ? $t->{"nova"} : $t->{"novas"}?></span>
                <span class="m-dropdown__header-subtitle"><?=count($newNotifications) == 1 ? $t->{"notificação"} : $t->{"notificações"}?></span>
            </div><?php } ?>
            <div class="m-dropdown__body">
                <div class="m-dropdown__content">
                    <ul class="nav nav-tabs m-tabs m-tabs-line m-tabs-line--brand" role="tablist">
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link active" data-toggle="tab" href="#topbar_notifications_notifications" role="tab">
                                <?=$t->{"Notificações"}?>
                            </a>
                        </li>
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link" data-toggle="tab" href="#topbar_notifications_logs" role="tab">
                                <?=$t->{"Logs"}?>
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="topbar_notifications_notifications" role="tabpanel">
                            <div class="m-scrollable" data-scrollable="true" data-height="250" data-mobile-height="200">

                                <div class="m-list-timeline--skin-light">
                                    <div class="m-list-timeline__items">
                                    <?php foreach ($newNotifications as $notification) { ?>
                                        <div class="m-list-timeline__item">
                                            <span class="m-list-timeline__badge m-list-timeline__badge--<?=$notification->type?>"><span class="m-badge m-badge--info m-badge--dot"></span></span>
                                            <span class="m-list-timeline__text" style="text-align: justify"><?=$notification->description?><?php if($notification->status != null) {?><span class="m-badge m-badge--<?=$notification->type?> m-badge--wide"> <?=$notification->status?></span><?php } ?></span>
                                            <span class="m-list-timeline__time"><?=fnTimeElapsed($notification->created_at, false, $user->language)?></span>
                                            <?php   $content = array("is_read" => json_encode(1), "id" => $notification->id);
                                            $update = Notification::save($content); ?>
                                        </div>
                                        <hr/>
                                    <?php } ?>
                                    <?php foreach ($oldNotifications as $notification) { ?>
                                        <div class="m-list-timeline__item">
                                            <span class="m-list-timeline__badge m-list-timeline__badge--<?=$notification->type?>"></span>
                                            <span class="m-list-timeline__text" style="text-align: justify"><?=$notification->description?> <?php if($notification->status != null) {?><span class="m-badge m-badge--<?=$notification->type?> m-badge--wide"> <?=$notification->status?></span><?php } ?></span>
                                            <span class="m-list-timeline__time"><?=fnTimeElapsed($notification->created_at, false, $user->language)?></span>
                                        </div>
                                        <hr/>
                                    <?php } ?>
                                    <?php if (count($newNotifications) < 1 && count($oldNotifications) < 1) {?>
                                        <p style="text-align: center"><?=$t->{"Nenhuma notificação ainda"}?></p>
                                    <?php } ?>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="tab-pane" id="topbar_notifications_logs" role="tabpanel">
                            <div class="m-scrollable" data-scrollable="true" data-height="250" data-mobile-height="200">
                                <div class="m-list-timeline m-list-timeline--skin-light">
                                    <div class="m-list-timeline__items">
                                    <?php foreach ($userLogs as $log) { ?>
                                        <div class="m-list-timeline__item">
                                            <span class="m-list-timeline__badge"></span>
                                            <span class="m-list-timeline__text"><?=$log->description?> <?php if($log->type != null) {?><span class="m-badge m-badge--<?=$log->type?> m-badge--wide"> <?=$log->status?></span><?php } ?></span>
                                            <span class="m-list-timeline__time"><?=fnTimeElapsed($log->created_at, false, $user->language)?></span>
                                        </div>
                                    <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</li>
