<div class="tab-pane active" id="m_quick_sidebar_tabs_messenger" role="tabpanel">
    <div class="m-messenger m-messenger--message-arrow m-messenger--skin-light">
        <div class="m-messenger__messages m-scrollable">
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-pic">
                        <img src="assets/app/media/img//users/user3.jpg" alt="" />
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                Megan wrote
                            </div>
                            <div class="m-messenger__message-text">
                                Hi Bob. What time will be the meeting ?
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Hi Megan. It's at 2.30PM
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-pic">
                        <img src="assets/app/media/img//users/user3.jpg" alt="" />
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                Megan wrote
                            </div>
                            <div class="m-messenger__message-text">
                                Will the development team be joining ?
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Yes sure. I invited them as well
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__datetime">2:30PM</div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-pic">
                        <img src="assets/app/media/img//users/user3.jpg" alt="" />
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                Megan wrote
                            </div>
                            <div class="m-messenger__message-text">
                                Noted. For the Coca-Cola Mobile App project as well ?
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Yes, sure.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Please also prepare the quotation for the Loop CRM project as well.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__datetime">3:15PM</div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-no-pic m--bg-fill-danger">
                        <span>M</span>
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                Megan wrote
                            </div>
                            <div class="m-messenger__message-text">
                                Noted. I will prepare it.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--out">
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-text">
                                Thanks Megan. I will see you later.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-messenger__wrapper">
                <div class="m-messenger__message m-messenger__message--in">
                    <div class="m-messenger__message-pic">
                        <img src="assets/app/media/img//users/user3.jpg" alt="" />
                    </div>
                    <div class="m-messenger__message-body">
                        <div class="m-messenger__message-arrow"></div>
                        <div class="m-messenger__message-content">
                            <div class="m-messenger__message-username">
                                Megan wrote
                            </div>
                            <div class="m-messenger__message-text">
                                Sure. See you in the meeting soon.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="m-messenger__seperator"></div>
        <div class="m-messenger__form">
            <div class="m-messenger__form-controls">
                <input type="text" name="" placeholder="Type here..." class="m-messenger__form-input">
            </div>
            <div class="m-messenger__form-tools">
                <a href="" class="m-messenger__form-attachment">
                    <i class="la la-paperclip"></i>
                </a>
            </div>
        </div>
    </div>
</div>