<?php

    ### INCLUDE
    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/internationalization/Translate.php";
    require_once "$root/panel/models/User.php";

    $t = new Translate();

    $user = unserialize($_SESSION['USER']);
    $refreshedUser = User::getUserById($user->id);

//    var_dump($refreshedUser->mail_notification);
?>
    <div class="tab-pane active" id="m_quick_sidebar_tabs_settings" role="tabpanel">
        <form class="m-login__form m-form" id="form-mail-notification">
            <div class="m-list-settings m-scrollable">
                <div class="m-list-settings__group">
                    <div class="m-list-settings__heading"><?=$t->{"Notificações por e-mail"}?></div>
                    <?php foreach ($refreshedUser->mail_notification as $notification) {?>
                        <div class="m-list-settings__item">
                            <span class="m-list-settings__item-label"><?=$t->{"$notification->name"}?></span>
                            <span class="m-list-settings__item-control">
                                <span class="m-switch m-switch--outline m-switch--icon-check m-switch--brand">
                                    <label>
                                        <input type="checkbox" <?=$notification->state == 1? "checked" : ""?> name="<?=$notification->name?>">
                                        <span></span>
                                    </label>
                                </span>
                            </span>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </form>
    </div>
    <script>
    window.onload = function(){

        $('#form-mail-notification input[type="checkbox"]').change(function(){

            var showMsg = function(type, msg) {

                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "hideDuration": "1000",
                    "timeOut": "2000",
                    "extendedTimeOut": "1000"
                };
                toastr[type](msg);
            }

            $.ajax({
                url: './actions/top-quick-sidebar-settings.php',
                type: 'POST',
                contentType: "application/x-www-form-urlencoded",
                data: { name: $(this).attr('name'), value: $(this).prop('checked') },
                success: function(response, status, xhr, $form) {

                    if (response.status == 1) {

                        showMsg(response.type, response.description);

                    } else {
                        showMsg(response.type, response.description);
                    }

                }
            });

        });

    }

    </script>