<?php

    ### INCLUDE
    $root = realpath($_SERVER["DOCUMENT_ROOT"]);
    require_once "$root/panel/models/LogApplication.php";
    require_once "$root/panel/models/LogServer.php";

    $t = new Translate();

    $user = unserialize($_SESSION['USER']);

    $application_logs = LogApplication::all("created_at >= '$user->created_at' ORDER BY created_at DESC LIMIT 10");
    $server_logs = LogServer::all();
?>

<div class="tab-pane" id="m_quick_sidebar_tabs_logs" role="tabpanel">
    <div class="m-list-timeline m-scrollable">
        <div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                <?=$t->{"Logs da Plataforma"}?>
            </div>
            <div class="m-list-timeline__items">
                <?php foreach ($application_logs as $appLog) { ?>
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--<?=$appLog->type?>"></span>
                    <label class="m-list-timeline__text"><?=$appLog->description?> <?php if($appLog->status != null) {?> <span class="m-badge m-badge--<?=$appLog->type?> m-badge--wide"><?=$appLog->status?></span><?php } ?> </label>
                    <span class="m-list-timeline__time"><?=fnTimeElapsed($appLog->created_at, false, $user->language)?></span>
                </div>
                <?php } ?>
                <?php if (count($application_logs) < 1) {?>
                    <p style="text-align: center"><?=$t->{"Nenhum log ainda"}?></p>
                <?php } ?>
            </div>
        </div>
        <div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                <?=$t->{"Logs do Servidor"}?>
            </div>
            <div class="m-list-timeline__items">
                <?php foreach ($server_logs as $serverLog) { ?>
                    <div class="m-list-timeline__item">
                        <span class="m-list-timeline__badge m-list-timeline__badge--<?=$serverLog->type?>"></span>
                        <label href="" class="m-list-timeline__text"><?=$serverLog->description?> <?php if($serverLog->status != null) { ?><span class="m-badge m-badge--<?=$serverLog->type?> m-badge--wide"><?=$serverLog->status?></span><?php } ?> </label>
                        <span class="m-list-timeline__time"><?=fnTimeElapsed($serverLog->created_at, false, $user->language)?></span>
                    </div>
                <?php } ?>
                <?php if (count($server_logs) < 1) {?>
                    <p style="text-align: center"><?=$t->{"Nenhum log ainda"}?></p>
                <?php } ?>
            </div>
        </div>
        <!--<div class="m-list-timeline__group">
            <div class="m-list-timeline__heading">
                Server Logs
            </div>
            <div class="m-list-timeline__items">
                <div class="m-list-timeline__item">
                    <span class="m-list-timeline__badge m-list-timeline__badge--state-success"></span>
                    <a href="" class="m-list-timeline__text">Production server up</a>
                    <span class="m-list-timeline__time">5 hrs</span>
                </div>
            </div>
        </div>-->
    </div>
</div>