<?php
    $t = new Translate();

    $user = unserialize($_SESSION['USER']);
    var_dump($user->username);
?>
<div class="tab-pane active" id="m_quick_sidebar_tabs_settings" role="tabpanel">
    <div class="m-list-settings m-scrollable">
        <div class="m-list-settings__group">
            <div class="m-list-settings__heading"><?=$t->{"Notificações por e-mail"}?></div>
            <div class="m-list-settings__item">
                <span class="m-list-settings__item-label"><?=$t->{"loggedIn"}?></span>
                <span class="m-list-settings__item-control">
										<span class="m-switch m-switch--outline m-switch--icon-check m-switch--brand">
											<label>
												<input type="checkbox" checked="checked" name="">
												<span></span>
											</label>
										</span>
									</span>
            </div>
        </div>
            <!--<div class="m-list-settings__group">
                <div class="m-list-settings__heading">System Settings</div>
                <div class="m-list-settings__item">
                    <span class="m-list-settings__item-label">System Logs</span>
                    <span class="m-list-settings__item-control">
                                            <span class="m-switch m-switch--outline m-switch--icon-check m-switch--brand">
                                                <label>
                                                    <input type="checkbox" name="">
                                                    <span></span>
                                                </label>
                                            </span>
                                        </span>
                </div>
            </div>-->
    </div>
</div>